name: Deploy app
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copiar archivos del proyecto (excluyendo node_modules y .git)
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' \
            -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" \
            ./ $SERVER_USER@$SERVER_IP:/var/www/mi-backend/

          # Conectar al servidor e instalar dependencias y reiniciar
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/mi-backend
            npm install --production
            pm2 restart mi-backend || pm2 start index.js --name mi-backend
          EOF

          rm private_key.pem
          echo "Deployment completed successfully."
